name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./cmd/...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./cmd/...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./cmd/...
        
    - name: Test
      run: go test -v ./cmd/...

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -o bot -ldflags '-w -s' ./cmd/...

deploy:
  - uses: actions/checkout@v3
  with:
    fetch-depth: 0
    ref: main
- uses: ayr-ton/git-deploy-action@v1.1
  with:
    # The SSH private key for SSH connection to the target repository.
    # We strongly recommend saving this value as a GitHub Secret and using deploy
    # keys within the target repository
    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    # The SSH-based URL to the target repository
    target_repo_url: ${{ secrets.TARGET_REPO_URL }}
    # The branch to push to the target repository, mandatory
    target_branch: dev
