name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./cmd/...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./cmd/...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      run: golint ./cmd/...
        
    - name: Test
      run: go test -v ./cmd/...


  deploy:
    runs-on: ubuntu-20.04
    needs: audit
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
      
    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -o ./bin/bot -ldflags '-w -s' ./cmd/...

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: master 
    - uses: wei/git-sync@v3
      with:
        source_repo: git@github.com:MarlikAlmighty/kickHisAss.git
        source_branch: "master"
        destination_repo: ssh://52.33.191.141/home/ubuntu/bot
        destination_branch: "dev"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 



